### ISSUE TITLE
The role fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by yabusygin** [yabusygin/ansible-role-gitlab#39]
The role fails on Ubuntu 16.04. The task "run GitLab" fails with the following exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/jsonschema/__init__.py", line 31, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1626001652.288977-9263-55526746718700/AnsiballZ_docker_compose.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1626001652.288977-9263-55526746718700/AnsiballZ_docker_compose.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1626001652.288977-9263-55526746718700/AnsiballZ_docker_compose.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.cloud.docker.docker_compose', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.5/runpy.py", line 196, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_docker_compose_payload_iwr670m0/ansible_docker_compose_payload.zip/ansible/modules/cloud/docker/docker_compose.py", line 483, in <module>
  File "/usr/local/lib/python3.5/dist-packages/compose/cli/command.py", line 6, in <module>
    from .. import config
  File "/usr/local/lib/python3.5/dist-packages/compose/config/__init__.py", line 3, in <module>
    from .config import ConfigurationError
  File "/usr/local/lib/python3.5/dist-packages/compose/config/config.py", line 48, in <module>
    from .validation import match_named_volumes
  File "/usr/local/lib/python3.5/dist-packages/compose/config/validation.py", line 8, in <module>
    from jsonschema import Draft4Validator
  File "/usr/local/lib/python3.5/dist-packages/jsonschema/__init__.py", line 33, in <module>
    import importlib_metadata as metadata
  File "/usr/local/lib/python3.5/dist-packages/importlib_metadata/__init__.py", line 66
    return f"No package metadata was found for {self.name}"
                                                          ^
SyntaxError: invalid syntax
```

**Comment by yabusygin** [comment]
Ubuntu 20.04 uses Python 3.5 by default. Also the latest version of `importlib_metadata` package is installed on the
managed host. The recent versions of `importlib_metadata` package use type annotations that are incompatible with Python 3.5. Therefore `docker_compose` Ansible module ("run GitLab" task) fails with the specified above exception.

The failure may be fixed by using `importlib_metadata` version 2.1.1:

```sh
python3 -m pip install importlib-metadata==2.1.1
```
